[package]
name = "awfuldb"
version = "0.1.0"
edition = "2021"

[dependencies]
rouille = "3.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3.3"
anyhow = "1.0"
rustc-hash = "1.1"
divrem = "1.0"
