[package]
name = "awfuldb"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
arrayvec = "0.7"
rkyv = { version = "0.7", features = ["archive_le"] } # size_64??
anyhow = "1.0"

[features]
default = []
#validation = ["rkyv/validation"]
